default: stutest.out

clean:
	rm *.out
	rm *.pyc
	ls

stutest.out: 
	python main.py stutest.in > stutest.out
	cat stutest.out

proftest.out:
	python main.py proftest.in > proftest.out
	cat proftest.out
